Fixed spellcheck errors

diff --git a/dls b/dls
--- a/dls
+++ b/dls
@@ -1,9 +1,5 @@
 #!/bin/sh
 
-EC='\033[0;31m' # Error color
-WC='\033[0;33m ' # Warning color
-NC='\033[0m' # No color
-
 DRY_RUN=0
 VERBOSE=0
 OVERWRITE_BROKEN_SYM_LINK=1; OVERWRITE_FOREIGN_SYM_LINK=0
@@ -11,14 +7,15 @@ OVERWRITE_FILES=0;
 
 WARN() {
         msg="$1"
-        printf "${WC}WARNING${NC}: $msg\n"
+        echo "WARNING: $msg"
 }
 
 ERR() {
-        msg="$1"; code=$2
-        printf "${EC}ERROR${NC}: $msg\n"
+        msg="$1"
+        code="$2"
+        echo "ERROR: $msg" >&2
         [ -z "$code" ] && return 1 # if no code is specified
-        exit $code
+        exit "$code"
 }
 
 Vecho() {
@@ -28,24 +25,24 @@ Vecho() {
 _LINK_FILES() {
         SOURCE_FILE=$1; SINK_FILE=$2
         [ "$DRY_RUN" -eq 1 ] && return 0
-        [ "$VERBOSE" -eq 1 ] && ln -srv $SOURCE_FILE $SINK_FILE
-        [ "$VERBOSE" -eq 0 ] && ln -sr $SOURCE_FILE $SINK_FILE
+        [ "$VERBOSE" -eq 1 ] && ln -srv "$SOURCE_FILE" "$SINK_FILE"
+        [ "$VERBOSE" -eq 0 ] && ln -sr "$SOURCE_FILE" "$SINK_FILE"
 }
 _CHECK_FILE() {
-        # 1 => SINK_FILE is a directory
-        # 2 => SINK_FILE Do not Exist (clean)
-        # 3 => SINK_FILE exits ( Non Sym link )
-        # 4 => SINK_FILE exits ( Broken Sym link )
-        # 5 => SINK_FILE points to SOURCE_FILE
-        # 6 => FILE exits ( Sym link but not pointing to SOURCE )
+        # 10 => SINK_FILE is a directory
+        # 20 => SINK_FILE Do not Exist (clean)
+        # 30 => SINK_FILE exits ( Non Sym link )
+        # 40 => SINK_FILE exits ( Broken Sym link )
+        # 50 => SINK_FILE points to SOURCE_FILE
+        # 60 => FILE exits ( Sym link but not pointing to SOURCE )
         SOURCE_FILE=$1; SINK_FILE=$2
 
-        [ -d "$SINK_FILE" ] && return 1
-        ls "$SINK_FILE" >/dev/null 2>&1 || return 2
-        [ -L "$SINK_FILE" ] || return 3
-        [ -e "$SINK_FILE" ] || return 4
-        [ "$SINK_FILE" -ef "$SOURCE_FILE" ] && return 5
-        [ "$SINK_FILE" -ef "$SOURCE_FILE" ] || return 6
+        [ -d "$SINK_FILE" ] && return 10
+        ls "$SINK_FILE" >/dev/null 2>&1 || return 20
+        [ -L "$SINK_FILE" ] || return 30
+        [ -e "$SINK_FILE" ] || return 40
+        [ "$(readlink -f "$SINK_FILE")" = "$(realpath "$SOURCE_FILE")" ] && return 50
+        [ "$(readlink -f "$SINK_FILE")" = "$(realpath "$SOURCE_FILE")" ] && return 60
 }
 
 _H_FILE() {
@@ -53,8 +50,8 @@ _H_FILE() {
         [ "$OVERWRITE_FILES" -eq 0 ] && ERR "File Exist $SINK_FILE ($SOURCE_FILE)"
         [ "$OVERWRITE_FILES" -eq 0 ] && return 1
         [ "$DRY_RUN" -eq 1 ] && return 0
-        [ "$OVERWRITE_FILES" -eq 1 ] && rm $SINK_FILE
-        _LINK_FILES $SOURCE_FILE $SINK_FILE
+        [ "$OVERWRITE_FILES" -eq 1 ] && rm "$SINK_FILE"
+        _LINK_FILES "$SOURCE_FILE" "$SINK_FILE"
 }
 
 _H_BROKEN_SYM_LINK() {
@@ -62,8 +59,8 @@ _H_BROKEN_SYM_LINK() {
         [ "$OVERWRITE_FILES" -eq 0 ] && \
                 ERR "A broken link Exist $SINK_FILE ($SOURCE_FILE)" || return 1
         [ "$DRY_RUN" -eq 1 ] && return 0
-        [ "$OVERWRITE_BROKEN_SYM_LINK" -eq 1 ] && rm $SINK_FILE
-        _LINK_FILES $SOURCE_FILE $SINK_FILE
+        [ "$OVERWRITE_BROKEN_SYM_LINK" -eq 1 ] && rm "$SINK_FILE"
+        _LINK_FILES "$SOURCE_FILE" "$SINK_FILE"
 }
 
 _H_FOREIGN_SYM_LINK() {
@@ -72,36 +69,36 @@ _H_FOREIGN_SYM_LINK() {
                 ERR "A foreign link Exist $SINK_FILE ($SOURCE_FILE)" || return 1
         [ "$OVERWRITE_FOREIGN_SYM_LINK" -eq 0 ] && return 1
         [ "$DRY_RUN" -eq 1 ] && return 0
-        [ "$OVERWRITE_FOREIGN_SYM_LINK" -eq 1 ] && rm $SINK_FILE
-        _LINK_FILES $SOURCE_FILE $SINK_FILE
+        [ "$OVERWRITE_FOREIGN_SYM_LINK" -eq 1 ] && rm "$SINK_FILE"
+        _LINK_FILES "$SOURCE_FILE" "$SINK_FILE"
 }
 
 LINK_FILE() {
         SOURCE_DIR=$1; SOURCE_FILE=$2; TARGET_DIR=$3;
 
         SINK_FILE="$(echo "$SOURCE_FILE" | sed "s|^$SOURCE_DIR/|$TARGET_DIR/|g")"
-        mkdir -p $(dirname $SINK_FILE) # Making source dir
-        _CHECK_FILE $SOURCE_FILE $SINK_FILE
+        mkdir -p "$(dirname "$SINK_FILE")" # Making source dir
+        _CHECK_FILE "$SOURCE_FILE" "$SINK_FILE"
         _CHECK_FILE_CODE=$?
 
          case $_CHECK_FILE_CODE in
-                 1)
+                 10)
                          ERR "$SINK_FILE is a directory can't link ($SOURCE_FILE)"
                          return 1;;
-                 2)
-                         _LINK_FILES $SOURCE_FILE $SINK_FILE
+                 20)
+                         _LINK_FILES "$SOURCE_FILE" "$SINK_FILE"
                          return 0;;
-                 3)
-                         _H_FILE $SOURCE_FILE $SINK_FILE
+                 30)
+                         _H_FILE "$SOURCE_FILE" "$SINK_FILE"
                          return $?;;
-                 4)
-                         _H_BROKEN_SYM_LINK $SOURCE $SINK_FILE
+                 40)
+                         _H_BROKEN_SYM_LINK "$SOURCE" "$SINK_FILE"
                          return $?;;
-                 5)
+                 50)
                          Vecho "$SOURCE_FILE => $SINK_FILE (already linked)"
                          return 0;;
-                 6)
-                         _H_FOREIGN_SYM_LINK $SOURCE_FILE $SINK_FILE
+                 60)
+                         _H_FOREIGN_SYM_LINK "$SOURCE_FILE" "$SINK_FILE"
                          return $?;;
                  *)
                          ERR "_CHECK_FILE returned unknown code ($_CHECK_FILE_CODE)" 1;;
@@ -112,17 +109,16 @@ UNLINK_FILE() {
         SOURCE_DIR=$1; SOURCE_FILE=$2; TARGET_DIR=$3;
 
         SINK_FILE="$(echo "$SOURCE_FILE" | sed "s|^$SOURCE_DIR/|$TARGET_DIR/|g")"
-        mkdir -p $(dirname $SINK_FILE) # Making source dir
-        _CHECK_FILE $SOURCE_FILE $SINK_FILE
+        _CHECK_FILE "$SOURCE_FILE" "$SINK_FILE"
         _CHECK_FILE_CODE=$?
 
          case $_CHECK_FILE_CODE in
-                 5)
+                 50)
                          Vecho "Deleted: $SINK_FILE (-> $SOURCE_FILE)"
                          [ "$DRY_RUN" -eq 1 ] && return 0
-                         rm $SINK_FILE
+                         rm "$SINK_FILE"
                          return 0;;
-                 2)
+                 20)
                          return 0;;
                  *)
                          ERR "cannot safely unlink file ($SINK_FILE) ($_CHECK_FILE_CODE)"
@@ -133,13 +129,12 @@ UNLINK_FILE() {
 
 FOR_EACH_FILE_IN_PKG() {
     FUNC=$1; SOURCE_DIR=$2; TARGET_DIR=$3
-    SOURCE_FILEs="$(find $SOURCE_DIR -type f)"
+    SOURCE_FILEs="$(find "$SOURCE_DIR" -type f)"
     return_code=0;
 
     for SOURCE_FILE in $SOURCE_FILEs
     do
-            $FUNC $SOURCE_DIR $SOURCE_FILE $TARGET_DIR
-            [ "$?" -ne 0 ] && return_code=1
+            $FUNC "$SOURCE_DIR" "$SOURCE_FILE" "$TARGET_DIR" || return_code=1
     done
     return $return_code
 }
@@ -153,14 +148,14 @@ CHECK_AND_RUN_FOR_PKGs() {
          for SOURCE_DIR in $SOURCE_DIRs
          do
                  [ -d "$SOURCE_DIR" ] || ERR "Cannot find folder '$SOURCE_DIR'!" 1
-                 FOR_EACH_FILE_IN_PKG $FUNC $SOURCE_DIR $TARGET_DIR || ERR "All Abort!" 1
+                 FOR_EACH_FILE_IN_PKG "$FUNC" "$SOURCE_DIR" "$TARGET_DIR" || ERR "All Abort!" 1
          done
 
          [ "$pDRY_RUN" -eq 1 ]  && return 0
          DRY_RUN=$pDRY_RUN && VERBOSE=$pVERBOSE
          for SOURCE_DIR in $SOURCE_DIRs
          do
-                 FOR_EACH_FILE_IN_PKG $FUNC $SOURCE_DIR $TARGET_DIR
+                 FOR_EACH_FILE_IN_PKG "$FUNC" "$SOURCE_DIR" "$TARGET_DIR"
          done
 }
 
@@ -169,7 +164,7 @@ TARGET_DIR="$HOME"
 
 useage() {
         echo "dls (dotfiles linking script) (compatible with GNU stow)
-POSIX compatible script. requirement: find, ls, ln
+POSIX compatible script. requirement: find, ls, ln, readlink, realpath
 
 SYNOPSIS:
 
@@ -191,11 +186,10 @@ OPTIONS:
 author: liupold <rohn.ch@gmail.com>
 "
 
+exit "$1"
 }
 
-TEMP=$(getopt -o 'hfblvnt:S:D:R:' --long 'help,overwrite-files,overwrite-broken,overwrite-link,verbose,simulate,target:,link:,delete:,re-link:' -n 'dls' -- "$@")
-
-[ "$?" -ne 0 ] && useage && exit 1
+TEMP=$(getopt -o 'hfblvnt:S:D:R:' --long 'help,overwrite-files,overwrite-broken,overwrite-link,verbose,simulate,target:,link:,delete:,re-link:' -n 'dls' -- "$@") || useage 1
 
 eval set -- "$TEMP"
 unset TEMP
@@ -240,6 +234,7 @@ while true; do
      esac
 done
 
+[ "$@" ] && ERR "Unrecognized trailing option '$*'" 1
 CHECK_AND_RUN_FOR_PKGs UNLINK_FILE "$D_ $R_" "$TARGET_DIR"
 CHECK_AND_RUN_FOR_PKGs LINK_FILE  "$S_ $R_" "$TARGET_DIR"
 
